california:
  name: "California"
  url: "http://goo.gl/WtOZY"
costa_rica:
  name: "Costa Rica"
  url: "http://goo.gl/1mNGw"
italy:
  name: "Italy"
  url: "https://s3.amazonaws.com/BattleTrip/Italy+honeymoon+new+design2.pdf"
