california:
  name: "Honeymoon in California"
  url: "http://goo.gl/WtOZY"
costa_rica:
  name: "Honeymoon in Costa Rica"
  url: "http://goo.gl/1mNGw"
italy:
  name: "Honeymoon in Italy"
  url: "https://s3.amazonaws.com/BattleTrip/Italy+honeymoon+new+design2.pdf"
