default:
  header: "<strong>A travel experience like no other.</STRONG>"
  subheader: "Let OutTrippin travel experts craft a unique holiday plan just for you."
  placeholder: "Where would you like to go?"
  submit: "Send me ideas!"
  process:
    text: "Have a better holiday and save hours of time researching.<br>Get a tailored travel plan from a OutTrippin expert."
    step1:
      title: "How does it work?"
      text: "Describe your travel personality, and the trip you have in mind and our experts will pitch you travel ideas."
    step2:
      title: "Who are the experts?"
      text: "Pro travel ploggers and writers who've been there, care and are ready to share all their best experiences."
    step3:
      title: "What do I get?"
      text: "A day-by-day trip plan, tailored to your personality full of tips, tricks and advice from a travel expert."
    step4:
      title: "Ready to book?"
      text: "OutTrippin helps make your unique holiday plan a reality with quick and easy bookings."
  pics:
    nz:
      title: "Lake Matheson, New Zealand"
      src: "1.jpg"
      text: "Famous for its reflected mirror views of Aoraki (Mt Cook) the tallest mountain in NZ."
      expert: "<a target='blank' href='/users/337'>Luke C.</a> from <a target='blank' href='http://www.top100experiences.com.au/'>top100experiences.com.au</a>"
      avatar: "http://fe5f910fe9492af904f7-d923a624db3b3940ce48298d73fff237.r75.cf1.rackcdn.com/uploads/user/avatar/337/thumb_578407_10150886493477463_1896779031_n.jpg"
    marseille:
      title: "Cours Julien, Marseille, France"
      src: "2.jpg"
      text: "This is the place to go if you're looking for a hip bar, alternative crafts or colourful street art."
      expert: "<a target='blank' href='users/166/'>Karl D.</a> from <a target='blank' href='http://hobography.net/'>hobography.net</a>"
      avatar: "http://fe5f910fe9492af904f7-d923a624db3b3940ce48298d73fff237.r75.cf1.rackcdn.com/uploads/user/avatar/166/thumb_karl.delandsheere.jpg"
    hawaii:
      title: "Mt. Wai'ale'ale, Kaua'i, Hawai'i"
      src: "3.jpg"
      text: "This ancient volcanic crater is one of the wettest spots on earth with 460 inches of annual rainfall!"
      expert: "<a target='blank' href='users/163'>Toccara B.</a> from <a target='blank' href='http://mytraveldays.com'>mytraveldays.com</a></a>"
      avatar: "http://fe5f910fe9492af904f7-d923a624db3b3940ce48298d73fff237.r75.cf1.rackcdn.com/uploads/user/avatar/163/thumb_Tuscany__302_.JPG"
    cmai:
      title: "Yi Peng Lantern Festival, Chiang Mai, Thailand"
      src: "4.jpg"
      text: "Bring a marker pen to write your dreams on the paper lanterns before sending them to the heavens."
      expert: "<a target='blank' href='users/133'>Chris B.</a> from <a target='blank' href='http://oneweirdglobe.com'>oneweirdglobe.com</a>"
      avatar: "http://fe5f910fe9492af904f7-d923a624db3b3940ce48298d73fff237.r75.cf1.rackcdn.com/uploads/user/avatar/172/thumb_Headshot_square_small.JPG"
    nyc:
      title: "Manhattan, New York City"
      src: "5.jpg"
      text: "To catch an iconic NYC yellow taxi, look at the roof light. If it's lit the taxi is ready to take your fare."
      expert: "<a target='blank' href='users/366'>Kellie N.</a> from <a target='blank' href='http://mydestinationunknown.com'>mydestinationunknown.com</a>"
      avatar: "http://fe5f910fe9492af904f7-d923a624db3b3940ce48298d73fff237.r75.cf1.rackcdn.com/uploads/user/avatar/366/thumb_296477_10150372870103436_1643175515_n.jpg"
    cmai2:
      title: "The Elephant Nature Park, Chiang Mai, Thailand"
      src: "6.jpg"
      text: "The park houses more than 1000 animals, they rescue any animal in need not just elephants."
      expert: "<a target='blank' href='users/133'>Chiara S.</a> from <a target='blank' href='http://www.lavencid.blogspot.com'>lavencid.com</a>"
      avatar: "http://fe5f910fe9492af904f7-d923a624db3b3940ce48298d73fff237.r75.cf1.rackcdn.com/uploads/user/avatar/132/thumb_CHIARITA.jpg"

honeymoon:
  header: "<strong>ZAP YOUR</strong><br/>HONEYMOON PLANNING<strong><br/>STRESS</strong>"
  subheader: "Let our travel experts compete to design a honeymoon tailored to your personality"
  placeholder: "Where would you like to go?"
  submit: "Launch a trip. It's free!"
  process:
    header: "Tailored honeymoon planning from a real travel expert!"
    step1:
      title: "Describe"
      text: "Tell us where and when you want to go and describe your travel style and personality."
    step2:
      title: "Pick"
      text: "Our travel writers & bloggers send you their best honeymoon ideas and you pick a favorite."
    step3:
      title: "Book"
      text: "Your chosen expert plans a tailored day-by-day trip plan that is all easily bookable."
  pics:
    rio:
      title: "Rio Sunset"
      src: "http://b8556536e41a83f2856c-9d3af255cebd1b18b21184d2df8a2f53.r11.cf1.rackcdn.com/frontpage/01_rio.jpg"
      text: "I have champagne and caviar tastes but I can also help you find the nitty gritty heart of Rio de Janeiro. Let me show you the best of both worlds!"
      expert: "Alexandra P."
      avatar: http://b8556536e41a83f2856c-9d3af255cebd1b18b21184d2df8a2f53.r11.cf1.rackcdn.com/frontpage/01_alexandra.jpeg
    maldives:
      title: "House on stilts in water — Maldives"
      src: "http://b8556536e41a83f2856c-9d3af255cebd1b18b21184d2df8a2f53.r11.cf1.rackcdn.com/frontpage/02_maldives.jpg"
      text: "I am the travel editor for a magazine and can recommend luxury vacations in the Maldives that promote responsible tourism."
      expert: "Aline D."
      avatar: "http://b8556536e41a83f2856c-9d3af255cebd1b18b21184d2df8a2f53.r11.cf1.rackcdn.com/frontpage/02_aline.png"
    cartagena:
      title: "Water umbrellas — Cartagena"
      src: "http://b8556536e41a83f2856c-9d3af255cebd1b18b21184d2df8a2f53.r11.cf1.rackcdn.com/frontpage/03_colombia.jpg"
      text: "I have uncovered local culinary delights and an enormous network of local connections to help you discover best bits of Cartagena de Indias and surrounds."
      expert: "Kristy E."
      avatar: "http://b8556536e41a83f2856c-9d3af255cebd1b18b21184d2df8a2f53.r11.cf1.rackcdn.com/frontpage/03_kristy.png"
    venice:
      title: "Venice"
      src: "http://b8556536e41a83f2856c-9d3af255cebd1b18b21184d2df8a2f53.r11.cf1.rackcdn.com/frontpage/04_venice.jpg"
      text: "To me, Venice means meandering through plazas and hidden alleyways, romantic gondola rides and restaurants well off the tourist track."
      expert: "Alena H."
      avatar: "http://b8556536e41a83f2856c-9d3af255cebd1b18b21184d2df8a2f53.r11.cf1.rackcdn.com/frontpage/04_Alena.png"
    santorini:
      title: "Santorini"
      src: "http://b8556536e41a83f2856c-9d3af255cebd1b18b21184d2df8a2f53.r11.cf1.rackcdn.com/frontpage/05_santorini.jpg"
      text: "I’m an ex-tour guide, turned travel writer and adore sharing unforgettable Greek adventures with visitors to my adopted country."
      expert: "Heidi F."
      avatar: "http://b8556536e41a83f2856c-9d3af255cebd1b18b21184d2df8a2f53.r11.cf1.rackcdn.com/frontpage/05_heidi.jpeg"