- 'Super planner'
- 'Anti planner'
- 'Penny pincher'
- 'Big spender'
- 'Slow roamer'
- 'History buff'
- 'Shopoholic'
- 'Humanitarian'
- 'Backpacker'
- 'Overpacker'
- 'Offbeat'
- 'Arty'
- 'Party'
- 'Adventurer'
- 'Daydreamer'
- 'Wifi wanderer'
- 'Worldly explorer'
- 'First time here'