- 'Luxury getaway'
- 'Beaches'
- 'Romantic retreat'
- 'Cultural immersion'
- 'Backpacking'
- 'Volunteering'
- 'City explorer'
- 'Local market & bazaars'
- 'Wildlife & ecology'
- 'Action & adventure'
- 'Foodie tours'
- 'Eco-friendly'
- 'Art & museums'
- 'Bus tours'
- 'Bike tours'
- 'Walking'
- 'Self-drive'
- 'Way off the beaten path'